dataSource:
  jeefwtwo:
    jdbcUrl: jdbc:sqlserver://192.168.0.104:1433;DatabaseName=jeefwtwo
    username: sa
    password: Passw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  adminManager:
    jdbcUrl: jdbc:sqlserver://192.168.0.104:1433;DatabaseName=AdminManager
    username: sa
    password: Passw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  QPAccountsDB:
    jdbcUrl: jdbc:sqlserver://192.168.0.104:1433;DatabaseName=QPAccountsDB
    username: sa
    password: Passw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  QPPlatformDB:
    jdbcUrl: jdbc:sqlserver://192.168.0.104:1433;DatabaseName=QPPlatformDB
    username: sa
    password: Passw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
logging:
  file: logs/admin.log
  level:
    com.mtf.admin.mapper: debug
server:
  port: 8080