dataSource:
  jeefwtwo:
    jdbcUrl: jdbc:sqlserver://192.168.0.106:1433;DatabaseName=jeefwtwo
    username: sa
    password: Passw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  manager:
    jdbcUrl: jdbc:sqlserver://192.168.0.106:1433;DatabaseName=manager
    username: sa
    password: Passw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver