spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=AdminManager
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Passw0rd
logging:
  file: logs/admin.log
  level:
    com.mtf.admin.mapper: debug
server:
  port: 8080