spring:
  datasource:
    url: jdbc:sqlserver://10.0.0.20:1433;DatabaseName=AdminManager
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Passw0rd
logging:
  file: logs/admin.log
  level:
    com.mtf.admin.mapper: debug
server:
  port: 8088
config:
  uploadPath: d:/qrcode